apiVersion: batch/v1
kind: Job
metadata:
  name: hello
spec:
  template:
    containers:
     - name: hello
       image: busybox
        args:
         - /bin/sh
         - -c
         - date; echo Hello from the Kubernetes cluster
    restartPolicy: Never
