--- 
apiVersion: batch/v1
kind: Job
metadata: 
  name: hello
spec: 
  template: 
    containers: 
      - 
        args: 
          - /bin/sh
          - "-c"
          - "date; echo Hello from the Kubernetes cluster"
        image: busybox
        name: hello
    restartPolicy: Never
