apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  template:
    spec:
      containers:
      - name: busybox
        image: busybox
        command:- date;echo Hello there
      restartPolicy: Never
  backoffLimit: 4

