apiVersion: v1
kind: Service
metadata:
  name: mynginxsvc
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30180
      name: http
    - port: 443
      nodePort: 31443
      name: https
  selector:
    myapp: mynginxapp
